### PR TITLE
Update README.md with authType SPN

### PR DESCRIPTION
**Pull request by sihegde**
I am proposing this change as the content didn't had any information on authType 'SPN' that we can use for Service Principal Authentication. The connection.cfg has details where it is mentioned that SPN should be used as authType. However, since README.md had no information provided on it, I have added those changes.

### CODE REVIEW

**Review by vibhansa-msft — COMMENTED** [review]
Thank you for your contribution. 
Under "Config file options" and "Environment Variables" sections these details are already present. We can detail it out in "Valid authentication" section as well, if that makes more sense for the user.

**Comment by sihegde** [comment]
Hi @vibhansa-msft ,

Thanks for the update! yes, both Config File options and Environment Variables sections have details about the Service principal authentication. However, it is bit confusing as there is no mention of 'authType' that has to be used for this. So I have added only 'authType' part.

**Comment by vibhansa-msft** [comment]
> Hi @vibhansa-msft ,
> 
> Thanks for the update! yes, both Config File options and Environment Variables sections have details about the Service principal authentication. However, it is bit confusing as there is no mention of 'authType' that has to be used for this. So I have added only 'authType' part.

Yes for the second part of the change I do agree with you.

**Comment by vibhansa-msft** [comment]
I will approve this change-set and merge. We will re-phrase the first part of your change-set if required.

**Review by vibhansa-msft — APPROVED** [review]

**Comment by sihegde** [comment]
@vibhansa-msft ,
Thank you!  sure..

**Pull request merged**
