### PR TITLE
added mp4 content-type

### PR DESCRIPTION
**Pull request by bo44arov**

### CODE REVIEW

**Review by vibhansa-msft — APPROVED** [review]

**Comment by vibhansa-msft** [comment]
This needs a CI pipeline to run before we can merge the changes. As you have forked the project I see pipeline is not able to run on that. I will try to take this changeset and fire a PR internally to make the required changes.

**Comment by vibhansa-msft** [comment]
This needs a CI pipeline to run before we can merge the changes. As you have forked the project I see pipeline is not able to run on that. I will try to take this changeset and fire a PR internally to make the required changes.

**Comment by bo44arov** [comment]
> This needs a CI pipeline to run before we can merge the changes. As you have forked the project I see pipeline is not able to run on that. I will try to take this changeset and fire a PR internally to make the required changes.

Great! Thanks for your help!

**Comment by vibhansa-msft** [comment]
Merged as PR : https://github.com/Azure/azure-storage-fuse/pull/663

**Pull request closed without merging**
