### PR TITLE
Publish logs from nightly pipeline

### PR DESCRIPTION
**Pull request by gapra-msft**

### CODE REVIEW

**Comment by tasherif-msft** [comment]
The reason we don't publish is because after enough runs we run of credits for our devops subscription, hence printing it out instead.

**Comment by gapra-msft** [comment]
oh let me add a flag that defaults to not printing - we can enable it when needed

**Comment by gapra-msft** [comment]
this is still useful when we need to debug

**Review by vibhansa-msft — APPROVED** [review]

**Review by souravgupta-msft — APPROVED** [review]

**Comment by tasherif-msft** [comment]
just to confirm we're defaulting to `false` on publishing here, correct?

**Comment by tasherif-msft** [comment]
just to confirm we're defaulting to `false` on publishing here, correct?

**Comment by gapra-msft** [comment]
> just to confirm we're defaulting to `false` on publishing here, correct?

working on doing this

**Review by tasherif-msft — APPROVED** [review]

**Pull request merged**
