### PR TITLE
test: add codespell github action

### PR DESCRIPTION
**Pull request by andyzhangx**
someone could help fix this?

https://github.com/andyzhangx/azure-storage-fuse/runs/5617634702?check_suite_focus=true
```
Error: ./cpplite.diff:680: existance ==> existence
Error: ./cpplite.diff:784: proerty ==> property, poetry
Error: ./cpplite.diff:1051: proerty ==> property, poetry
Error: ./cpplite.diff:1059: proerty ==> property, poetry
Error: ./cpplite.diff:1063: existance ==> existence
Error: ./cpplite.diff:4020: timout ==> timeout
Error: ./cpplite.diff:4026: timout ==> timeout
Error: ./cpplite.diff:7462: transfered ==> transferred
Error: ./cpplite.diff:9859: needeed ==> needed
Error: ./cpplite.diff:10005: BA ==> BY, BE
Error: ./cpplite.diff:10291: addded ==> added
Error: ./cpplite.diff:11089: BA ==> BY, BE
Error: ./CMakeLists.txt:177: enviroment ==> environment
Error: ./azure-pipelines.yml:88: seperate ==> separate
Error: ./blobfuse-nightly.yml:144: contianer ==> container
Error: ./blobfuse-nightly.yml:661: flie ==> file
Error: ./README.md:14: Authenicates ==> Authenticates
Error: ./README.md:69: milisecond ==> millisecond
Error: ./README.md:74: envrionment ==> environment
Error: ./README.md:76: naximum ==> maximum
Error: ./README.md:77: AKS ==> ASK
Error: ./README.md:85: supress ==> suppress
Error: ./README.md:176: accomodate ==> accommodate
Error: ./blobfuse-artifacts.yml:193: Debain ==> Debian
Error: ./test/oauthtokentests.cpp:69: upto ==> up to
Error: ./test/oauthtokentests.cpp:107: upto ==> up to
Error: ./test/oauthtokentests.cpp:136: upto ==> up to
Error: ./test/oauthtokentests.cpp:164: upto ==> up to
Error: ./test/feature_test.go:56: configued ==> configured
Error: ./test/feature_test.go:78: contianer ==> container
Error: ./test/feature_test.go:229: configued ==> configured
Error: ./test/feature_test.go:290: contianer ==> container
Error: ./test/feature_test.go:580: configued ==> configured
Error: ./test/tests.py:602: fo ==> of, for
Error: ./test/tests.py:1101: direcotry ==> directory
Error: ./test/tests.py:1220: aboslute ==> absolute
Error: ./test/tests.py:[18](https://github.com/andyzhangx/azure-storage-fuse/runs/5617634702?check_suite_focus=true#step:4:18)40: Ingoring ==> Ignoring
Error: ./test/not-automated/multi_open_test.py:26: stil ==> still
Error: ./test/not-automated/multiprocessing-threading/multiprocessfilenoupdates.py:2: trigerred ==> triggered
Error: ./test/not-automated/multiprocessing-threading/multiprocessfilenoupdates.py:4: triggerred ==> triggered
Error: ./stresstests/blobfusestress.cpp:184: recusrive ==> recursive
Error: ./stresstests/blobfusestress.cpp:188: performace ==> performance
Error: ./stresstests/blobfusestress.cpp:222: currnt ==> current
Error: ./stresstests/README.md:3: albiet ==> albeit
Error: ./stresstests/README.md:15: doesn' ==> doesn't
Error: ./cpplite/src/utility.cpp:203: BA ==> BY, BE
Error: ./cpplite/src/blob/blob_client.cpp:78: transfered ==> transferred
Error: ./cpplite/adls/include/json.hpp:6978: endianess ==> endianness
Error: ./cpplite/adls/include/json.hpp:7116: endianess ==> endianness
Error: ./cpplite/adls/include/json.hpp:12557: endianess ==> endianness
Error: ./cpplite/adls/include/json.hpp:12620: endianess ==> endianness
Error: ./cpplite/include/http/libcurl_http_client.h:[19](https://github.com/andyzhangx/azure-storage-fuse/runs/5617634702?check_suite_focus=true#step:4:19)5: timout ==> timeout
Error: ./cpplite/include/blob/blob_client.h:327: fro ==> for, from
Error: ./cpplite/include/blob/blob_client.h:353: wrappered ==> wrapped
Error: ./cpplite/include/blob/blob_client.h:355: wrappered ==> wrapped
Error: ./cpplite/include/blob/blob_client.h:449: existance ==> existence
Error: ./cpplite/include/blob/blob_client.h:533: existance ==> existence
Error: ./blobfuse/generaterpm.sh:30: vrsion ==> version
Error: ./blobfuse/utilities.cpp:139: seperators ==> separators
Error: ./blobfuse/utilities.cpp:155: untill ==> until
Error: ./blobfuse/fileapis.cpp:49: seperate ==> separate
Error: ./blobfuse/fileapis.cpp:272: untill ==> until
Error: ./blobfuse/fileapis.cpp:352: untill ==> until
Error: ./blobfuse/fileapis.cpp:384: untill ==> until
Error: ./blobfuse/fileapis.cpp:619: untill ==> until
Error: ./blobfuse/fileapis.cpp:637: trucate ==> truncate
Error: ./blobfuse/blobfuse.cpp:430: intialized ==> initialized
Error: ./blobfuse/directoryapis.cpp:13: seperators ==> separators
Error: ./blobfuse/directoryapis.cpp:68: seperators ==> separators
Error: ./blobfuse/directoryapis.cpp:74: uplaoded ==> uploaded
Error: ./blobfuse/directoryapis.cpp:221: retreived ==> retrieved
Error: ./blobfuse/directoryapis.cpp:251: seperators ==> separators
Error: ./blobfuse/src/OAuthTokenCredentialManager.cpp:551: folow ==> follow
Error: ./blobfuse/src/BlobStreamer.cpp:39: untill ==> until
Error: ./blobfuse/src/BlobStreamer.cpp:235: retreives ==> retrieves
Error: ./blobfuse/src/BlobStreamer.cpp:267: retreives ==> retrieves
Error: ./blobfuse/src/BlobStreamer.cpp:274: retreived ==> retrieved
Error: ./blobfuse/src/AttrCacheBfsClient.cpp:158: emptry ==> empty
Error: ./blobfuse/src/AttrCacheWrapper.cpp:316: existance ==> existence
Error: ./blobfuse/src/BlobfuseGlobals.cpp:47: thats ==> that's
Error: ./blobfuse/src/BlobfuseGlobals.cpp:50: thats ==> that's
Error: ./blobfuse/src/BlockBlobBfsClient.cpp:422: Unforseen ==> Unforeseen
Error: ./blobfuse/src/BlockBlobBfsClient.cpp:424: Unforseen ==> Unforeseen
Error: ./blobfuse/src/BlockBlobBfsClient.cpp:1001: retreived ==> retrieved
Error: ./blobfuse/include/AttrCacheWrapper.h:258: existance ==> existence
Error: ./nlohmann-json/json.hpp:6978: endianess ==> endianness
Error: ./nlohmann-json/json.hpp:7116: endianess ==> endianness
Error: ./nlohmann-json/json.hpp:12557: endianess ==> endianness
Error: ./nlohmann-json/json.hpp:126[20](https://github.com/andyzhangx/azure-storage-fuse/runs/5617634702?check_suite_focus=true#step:4:20): endianess ==> endianness
Codespell found one or more problems
```

### CODE REVIEW

**Comment by vibhansa-msft** [comment]
This is for v1, can you set this action for main branch instead. We can fix things for v2 there.

**Comment by andyzhangx** [comment]
> This is for v1, can you set this action for main branch instead. We can fix things for v2 there.

@vibhansa-msft it passes on main branch

**Comment by vibhansa-msft** [comment]
Your intention was to do this action on v2 code or v1? For v2, we can integrate this action as regular CI. If that's ok with you, you can edit the PR and make it based on "main" branch instead of "master"

**Comment by gapra-msft** [comment]
I tried to change the branch to main but looks like there are some conflicts. Please target the PR to main as Vikas mentioned

**Comment by andyzhangx** [comment]
new PR: https://github.com/Azure/azure-storage-fuse/pull/744, close this PR now

**Pull request closed without merging**
