### PR TITLE
Timeout

### PR DESCRIPTION
**Pull request by asorrin-msft**
This is a minor change on top of https://github.com/Azure/azure-storage-fuse/pull/146/files.  It sets different timeouts on different operations (5 seconds for most operations, 30 seconds for listing & larger-payload operations.)  Logic for data operations (put blob, put block, get blob) is unchanged.

### CODE REVIEW

**Comment by AlexanderYukhanov** [comment]
are timeout setting autoreset after a request has been completed?

**Comment by seguler** [comment]
I am not sure what you mean @AlexanderYukhanov - why would we reset any timeout setting ? Isn't it an absolute number every time ? E.g. 5 second for each get blob properties request.

**Comment by seguler** [comment]
@asorrin-msft @rickle-msft ; Alex has a good point. This curl handle is being reused all the time... Does the timeout get reset ? For instance, if you have listed blobs in 10 seconds, and then used the same handle for a large file upload. Would it timeout ? Has this been tested ?

**Comment by asorrin-msft** [comment]
Latest commit should fix any potential issues by resetting the values to zero (meaning "no timeout", according to libcurl docs)

**Comment by AlexanderYukhanov** [comment]
LGTM

**Comment by seguler** [comment]
lgtm

**Pull request merged**
