### PR TITLE
Initial changes for fuse 3 support

### PR DESCRIPTION
**Pull request by cris-b**
This makes it possible to conditionally build against fuse3, prinicipally so that FUSE_CAP_AUTO_INVAL_DATA can be used (see #668)

This results in a working file system for me when building against fuse 3, although I havent extensively tested it.

if AZS_FUSE3 environment variable is defined before running build.sh fuse3 will be used.  

I have left in fuse 2 code path because it seems fuse 2 would still need to be used for some of the older supported OS's (I'm using the OS's that are included in the binary build artifacts on the release page as a guide for what is supported 'officially'):

* Debian 9 (EOL June 2022)
* Ubuntu 18.04 (EOL April 2023)

I defined FUSE_USE_VERSION to 34 if using fuse3, as Debian 10 is the oldest supported OS which contains fuse 3, and that uses 3.4.1

There are zero changes to the code when building against fuse 2.

### CODE REVIEW

**Comment by vibhansa-msft** [comment]
Thanks for integrating fuse3 in blobfuse. We are close to our release cycle so will not take this PR up for the next release but will discuss internally on how to proceed with this.

**Comment by cris-b** [comment]
following 1.4.2 is there any any update on this?

**Comment by vibhansa-msft** [comment]
@cris-b : no plans for fuse3 so far, will keep this PR in open state only. If you need this for your use case you can continue using your forked branch.

**Comment by vibhansa-msft** [comment]
Problem with this change right now is its compile time check, so going this path we need to release two binaries one with fuse2 option and one with fuse3. Moving completely to fuse3 poses another issue that many older linux distros do not support it.

**Comment by cris-b** [comment]
but as mentioned in the comments

a - you already produce a different packages for different linux distros, and you dont produce 'generic' binaries.  Anyone not using one of those distros already has to compile themselves, in which case they get to choose.
b - only 2 of those distros do not support fuse 3 (debian 9, ubuntu 18.04), and ubuntu 9 is eol in six months.

so surely compiling for fuse 3 with all the distros except the above is no different to compiling a different binary for difference distros anyway?

**Comment by vibhansa-msft** [comment]
As you pointed out fuse3 is not supported on ubn-18 and deb-9, so for these distros we need to compile with fuse2 and rest with fuse3. Now the customers who are on updated distros takes our latest release will suddenly start observing failure as blobfuse will look for fuse3 while customers have fuse2 installed. So we will have to request all customers also to move to fuse3. My point here is its a breaking change, this upgrade from fuse2 to fuse3 can not be seamless. Also for customers who have been using fuse2 for long, do not get any significant advantage by moving to fuse3 and hence they may not show much interest in upgrading and potentially de-stabilizing the system.

**Comment by cris-b** [comment]
but as you are providing distro packages for all those distros (which specify their deps as requirements), it doesn't matter to the end user whether it pulls in fuse2 or 3 - it should be transparent.  both of them can co-exist happily and they should not notice the difference.

from the last libfuse 2 release (2.9.9) almost 3 years ago:
```Note: This is a maintenance release from the 2.9 branch of libfuse. Users are encouraged to transition to the
actively developed libfuse 3.x.```


libfuse3 was released 5 years ago.  It should also be noted that we are talking about the userspace library here, the kernel moves on regardless.

libfuse2 is essentially unmaintained at this point.

**Comment by vibhansa-msft** [comment]
We have just previewed our next generation of blobfuse (https://github.com/Azure/azure-storage-fuse/releases/tag/blobfuse2-2.0.0-preview.1). It is fuse3 compliant and does enable FUSE_CAP_AUTO_INVAL_DATA by default. Closing this PR as we will not be backporting this feature to blobfuse.

**Pull request closed without merging**
