### PR TITLE
Fix 32 bits build

### PR DESCRIPTION
**Pull request by AlexanderYukhanov**

### CODE REVIEW

**Comment by AlexanderYukhanov** [comment]
tested on 32 bit ubuntu 16.04

**Comment by raphaelm22** [comment]
Hi @AlexanderYukhanov 
I tried compiling on raspberry:
```
root@raspberrypi:~/azure-storage-fuse # git pull origin pull/19/head
remote: Counting objects: 175, done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 175 (delta 23), reused 38 (delta 17), pack-reused 123
Receiving objects: 100% (175/175), 152.79 KiB | 0 bytes/s, done.
Resolving deltas: 100% (68/68), done.
From https://github.com/Azure/azure-storage-fuse
 * branch            refs/pull/19/head -> FETCH_HEAD
root@raspberrypi:~/azure-storage-fuse # ./build.sh
./build.sh: line 9: cmake3: comando não encontrado
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CURL: /usr/lib/arm-linux-gnueabihf/libcurl.so (found version "7.38.0")
-- Found GnuTLS: /usr/lib/arm-linux-gnueabihf/libgnutls.so (found version "3.3.8")
-- Configuring done
-- Generating done
-- Build files have been written to: /root/azure-storage-fuse/build
Scanning dependencies of target blobfuse
[  3%] Building CXX object CMakeFiles/blobfuse.dir/blobfuse/blobfuse.cpp.o
[  6%] Building CXX object CMakeFiles/blobfuse.dir/blobfuse/fileapis.cpp.o
[  9%] Building CXX object CMakeFiles/blobfuse.dir/blobfuse/directoryapis.cpp.o
[ 12%] Building CXX object CMakeFiles/blobfuse.dir/blobfuse/utilities.cpp.o
[ 15%] Building CXX object CMakeFiles/blobfuse.dir/azure-storage-cpp-lite/src/base64.cpp.o
/root/azure-storage-fuse/azure-storage-cpp-lite/src/base64.cpp: In function ‘std::vector<unsigned char> microsoft_azure::storage::from_base64(const string&)’:
/root/azure-storage-fuse/azure-storage-cpp-lite/src/base64.cpp:100:28: error: comparison is always false due to limited range of data type [-Werror=type-limits]
                     if (ch < 0)
                            ^
/root/azure-storage-fuse/azure-storage-cpp-lite/src/base64.cpp:120:37: error: comparison is always false due to limited range of data type [-Werror=type-limits]
                             if (ch2 < 0)
                                     ^
cc1plus: all warnings being treated as errors
CMakeFiles/blobfuse.dir/build.make:158: recipe for target 'CMakeFiles/blobfuse.dir/azure-storage-cpp-lite/src/base64.cpp.o' failed
make[2]: *** [CMakeFiles/blobfuse.dir/azure-storage-cpp-lite/src/base64.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/blobfuse.dir/all' failed
make[1]: *** [CMakeFiles/blobfuse.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by AlexanderYukhanov** [comment]
Tested on raspberry pi (arm32)

**Comment by seguler** [comment]
Sorry - can you send this to dev branch instead ?

**Comment by AlexanderYukhanov** [comment]
will do

**Pull request closed without merging**
