### PR TITLE
feat: add AZURE_BLOB_ENDPOINT env support

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR add `AZURE_BLOB_ENDPOINT` env to support different azure env

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Release note**:
```
feat: add AZURE_BLOB_ENDPOINT env support
```

### CODE REVIEW

**Comment by andyzhangx** [comment]
@seguler I found there is even on build test on this repo?

**Comment by amnguye** [comment]
On the second part of the page, it shows you how to build the source
https://github.com/Azure/azure-storage-fuse/wiki/1.-Installation

As for the tests, you can add to the python tests.

**Comment by andyzhangx** [comment]
@amnguye thanks for the hint, I could compile now. 
Why not put this build process into CI pipeline, so it would automatically build for every PR. I could help do that if you could add me as repo admin, it only needs a little work.
Without CI, new PR may break build easily.

**Comment by andyzhangx** [comment]
I have verified this PR works well in Azure China Cloud by:
```
export AZURE_BLOB_ENDPOINT=andyeast2.blob.core.chinacloudapi.cn
export AZURE_STORAGE_ACCOUNT=andyeast2
export AZURE_STORAGE_ACCESS_KEY=...
mkdir blob
./blobfuse blob --container-name=public --tmp-path=/tmp/blobfuse/
```

Pls note that the AZURE_BLOB_ENDPOINT format should be `accountname.blob.core.chinacloudapi.cn` for Azure China Cloud

**Comment by amnguye** [comment]
I know you verified it with a working account and endpoint but I cannot approve this PR unless you write tests for this new feature. In the test you don't have to add in an actual account, key or endpoint, it can just be example text.

**Comment by andyzhangx** [comment]
> I know you verified it with a working account and endpoint but I cannot approve this PR unless you write tests for this new feature. In the test you don't have to add in an actual account, key or endpoint, it can just be example text.

Hi @amnguye I am not sure how to add such a test into https://github.com/Azure/azure-storage-fuse/blob/master/blobfuse/tests.py, could you help? Thanks.

**Pull request merged**
